// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250622192439_MakeDateCreatedOptional")]
    partial class MakeDateCreatedOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "With bros",
                            DateCreated = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Went hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "123",
                            DateCreated = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Drove"
                        },
                        new
                        {
                            Id = 3,
                            Content = "abc",
                            DateCreated = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Diving"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
